# -*- coding: utf-8 -*-
"""First Round of Presidential Elections in Brazil 2018 - Lucas Gomes Dantas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/177O-lMxW7SqzMS0H7K_9SCc29ZSvDBzW
"""

# Piece of code provided by Ivanovitch Medeiros Dantas da Silva
# Upload the data set to Colab

from google.colab import files
uploaded = files.upload()
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

"""# 1 - Initializing the work station

First, we must import the libraries and read into a pandas dataframe the data we are going to use.
"""